name: Run Automated Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout todolist APP
      - uses: actions/checkout@v3

      - name: Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Deps
        run: 
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Checkout test repo
        run: git clone https://github.com/mamunetond/Taller4.git
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install tests deps
        run: 
          cd Taller4
          npm ci

      - name: Install Playwright Browsers
        run: npx Playwright install --with-deps

      - name: Run Playwright tests
        run: 
          cd Taller4
          npx playwright test todolist.spec.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Taller4/playwright-report/
          retention-days: 1